### ISSUE TITLE
[Bug] Crash on Placement of Air Marker

### ISSUE THREAD

**Issue by Yulife** [AtomicBlom/SchematicaModderExtensions#1]
I placed the Air Marker in a building in my world and let it running. There were some holes which resulted in the entire chunk being filled with the Red Blocks. This lead to a [crash](http://puu.sh/fUj6H/e8f5db9d56.txt) that continues to happen on world entering.

Forge 1307
[Modlist](http://puu.sh/fUjGB/7c06a01570.png)

**EDIT:** Disabled Fastcraft, Optifine and Shaders. Not it does not crash anymore..

**Comment by AtomicBlom** [comment]
Bugger. Sorry @Yulife, the puush expired so I don't have a copy of the crash log anymore, I'll have to close this bug unless you happen to still have the world and can reproduce the log.

**Comment by Yulife** [comment]
Hehe, I added an EDIT. It was Optifine :)
